### ISSUE TITLE
HTML Comments

### ISSUE THREAD

**Issue by jim-rosales** [markAnthonyDay/prj-rev-bwfs-dasmoto#1]
Great job commenting your HTML file!

https://github.com/markAnthonyDay/prj-rev-bwfs-dasmoto/blob/3e386065759778463b7bc6591d44f0f3c09a4c63/Dasmotos/index.html#L10

**Comment by markAnthonyDay** [comment]
Thanks for all of your feedback. When someone creates an issue or comments on an issue, is an email automatically sent to the GitHub user? Otherwise how is a person notified?

**Comment by jim-rosales** [comment]
You're Welcome! I don't believe you receive an email when an issue is opened in your repo. I do receive notifications for comments in an issue considering I was the one that opened the issue. 

Anyhow you should receive a notification from Codecademy that your project has been reviewed which lets you know issues have been opened in your repository.
